### ISSUE TITLE
Android 4.4 Support

### ISSUE THREAD

**Issue by yaronby** [okamototk/jqm-mobile-bookmark-bubble#12]
Android 4.4 has a much easier way to add to home screen.

You can do it with only two taps as shown below:
http://prntscr.com/3e6i6u

Are there any plans of updating the code to support that ?

**Comment by okamototk** [comment]
I commited android4.4-support branch. I don't test so much. If you check it, I'm glad!

**Comment by yaronby** [comment]
Thanks for the super fast response !!

It works fine on my Android 4.4.

I would add some visual padding or a new line, have a look:
http://prntscr.com/3e6ss4

When do you intend to put it on the main source code ?

**Comment by okamototk** [comment]
Thanks for quick response too:)
I updated android4.4-support branch. Please check it!

**Comment by yaronby** [comment]
Notice this line break -
http://prntscr.com/3e7am5

**Comment by okamototk** [comment]
Sorry, not sooner reply. I commit the new code. Please check it.

**Comment by yaronby** [comment]
Works fine on my Nexus 4 :-)

Do you have plans to merge it with the main code ?

**Comment by okamototk** [comment]
Just now:)

**Comment by yaronby** [comment]
Well done, thanks
